### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by SidVal** [thejungwon/MyChromeExtension#1]
It's very important here on GitHub
Just explain what is this repo, and add a link to your [Medium's Post](https://medium.com/@thejungwon/best-html-css-javascript-practice-chrome-extension-ae4e5e7839e) for more info.

Great practice!

Thank you!

**Comment by thejungwon** [comment]
Thank you for your suggestion. I just did it!

**Comment by SidVal** [comment]
Great.

Don't forget edit the description and add topics on github main repo: https://github.com/thejungwon/MyChromeExtension

Now said: _No description, website, or topics provided._

**Comment by thejungwon** [comment]
> Great.
> 
> Don't forget edit the description and add topics on github main repo: https://github.com/thejungwon/MyChromeExtension
> 
> Now said: _No description, website, or topics provided._

Thank you!
